### ISSUE TITLE
报告python mode的一个bug

### ISSUE THREAD

**Issue by lynnux** [manateelazycat/grammatical-edit#1]
新建一个py文件打开，空白内容第一行随便输入个单词，然后到行首按C-K后者C-D删除，提示"Beginning of buffer"

环境:win7 64, gccemacs Emacs 29.0.50 (build 1, x86_64-w64-mingw32)

**Comment by lynnux** [comment]
c++ mode也是，行首开头按ENTER也是一样的不能执行操作。

**Comment by lynnux** [comment]
```
(define-key grammatical-edit-mode-map (kbd "M-p") 'grammatical-edit-jump-right)
(define-key grammatical-edit-mode-map (kbd "M-n") 'grammatical-edit-jump-left)
```
这两个是不是该交换下呢

**Comment by lynnux** [comment]
另外，大佬，有没有类似smartparens的sp-splice-sexp功能啊，比如 (aaaaa   (bbb|bb))  在|的位置执行sp-splice-sexp变成 (aaaaa bbbbb)

**Comment by manateelazycat** [comment]
> 另外，大佬，有没有类似smartparens的sp-splice-sexp功能啊，比如 (aaaaa (bbb|bb)) 在|的位置执行sp-splice-sexp变成 (aaaaa bbbbb)

grammatical-edit-unwrap

**Comment by manateelazycat** [comment]
jjj

> ```
> (define-key grammatical-edit-mode-map (kbd "M-p") 'grammatical-edit-jump-right)
> (define-key grammatical-edit-mode-map (kbd "M-n") 'grammatical-edit-jump-left)
> ```
> 
> 这两个是不是该交换下呢

这个是我的习惯，你可以自己自定义

**Comment by manateelazycat** [comment]
你说的问题已经修复了，谢谢反馈。

**Comment by lynnux** [comment]
@manateelazycat 感谢，测试OK。
还有问题，当有region时，`grammatical-edit-kill`好像不执行delete region操作，是设计如此吗？

**Comment by manateelazycat** [comment]
> @manateelazycat 感谢，测试OK。 还有问题，当有region时，`grammatical-edit-kill`好像不执行delete region操作，是设计如此吗？

已经修复了。

**Comment by lynnux** [comment]
nice!
另外我发现没装elisp，开启grammatical-edit编辑好像基本上都是正常的，奇怪了

**Comment by lynnux** [comment]
老大，又发现一个bug。
我在python virtula env中安装eaf，提示
```
ERROR: Can not perform a '--user' install. User site-packages are not visible in
 this virtualenv.
```
于是我想修改 https://github.com/emacs-eaf/emacs-application-framework/blob/master/install-eaf.py#L111 这里去掉--user参数，结果那个'--user'字符串很不好删除。

**Comment by manateelazycat** [comment]
> 老大，又发现一个bug。 我在python virtula env中安装eaf，提示
> 
> ```
> ERROR: Can not perform a '--user' install. User site-packages are not visible in
>  this virtualenv.
> ```
> 
> 于是我想修改 https://github.com/emacs-eaf/emacs-application-framework/blob/master/install-eaf.py#L111 这里去掉--user参数，结果那个'--user'字符串很不好删除。

不要在 python virual 中用EAF, 会有一堆bug, 而且不要在这个项目中去报另外一个项目的bug, 这里是 github 项目，不是聊天室。

**Comment by lynnux** [comment]
我是举个例子，上面那个'--user'用grammatical-edit编辑，不用region选中删除的话，不好删除掉啊

**Comment by manateelazycat** [comment]
> ERROR: Can not perform a '--user' install. User site-packages are not visible in
>  this virtualenv.

这个例子我没有看懂，在新的 Issue 里面提交的完整点吧，不知道你说的什么问题。

这个Issue就不要评论了，谢谢。
