### ISSUE TITLE
这处代码没起到对应作用，请问是 bug 还是特性？

### ISSUE THREAD

**Issue by dalugm** [manateelazycat/grammatical-edit#14]
大佬，我刚用你的这个插件，我是个 elisp 新手，有一处代码的作用我不太明白，请问是 bug 还是起什么我不知道的作用？

https://github.com/manateelazycat/grammatical-edit/blob/f6906655cd4ac36bdccfebea67c6da8cf7fb13d6/grammatical-edit.el#L1293

在我提交 pr 之前，这一处代码是 `(point-at-eol nil)`，但就我所知，这个函数（包括新用的这个 `line-end-position`）始终会返回一个值，放在 `(and ...)` 中判断相当于一直是 `t`，无法起到判断的作用。

如果是判断当前光标位置是否在行尾的话，不应该是用

```emacs lisp
(eq (line-end-position) (point))
```

来判断吗？希望大佬能解答我的疑惑

**Comment by manateelazycat** [comment]
那上个补丁我估计要撤销。

**Comment by manateelazycat** [comment]
emacs29很多警告都是不合适的

**Comment by dalugm** [comment]
我的意思是：之前用的`point-at-bol`，跟现在用的`line-end-position`，在通过 `(and ...)` 判断的时候都会返回一个数值，实际上是不起作用的（也就是说，即便撤回了上个补丁，也还是跟现在一样的效果）

疑问是：这里这样写的目的是什么

**Comment by manateelazycat** [comment]
> 大佬，我刚用你的这个插件，我是个 elisp 新手，有一处代码的作用我不太明白，请问是 bug 还是起什么我不知道的作用？
> 
> https://github.com/manateelazycat/grammatical-edit/blob/f6906655cd4ac36bdccfebea67c6da8cf7fb13d6/grammatical-edit.el#L1293
> 
> 在我提交 pr 之前，这一处代码是 `(point-at-eol nil)`，但就我所知，这个函数（包括新用的这个 `line-end-position`）始终会返回一个值，放在 `(and ...)` 中判断相当于一直是 `t`，无法起到判断的作用。
> 
> 如果是判断当前光标位置是否在行尾的话，不应该是用
> 
> ```emacs-lisp
> (eq (line-end-position) (point))
> ```
> 
> 来判断吗？希望大佬能解答我的疑惑

我之间的代码是 `(and (point-at-eol) ...` 没有写过 `(and (point-at-eol nil) ...` 这种形式。 

而是上个补丁 point-at-eol 改成 line-end-position 后， 引入了大量 `line-end-position nil`

上个补丁的质量还要多测试一下， 我暂时回滚了。

![截图 2022-10-02 15-23-12](https://user-images.githubusercontent.com/237487/193442913-e94be250-04dc-4306-a74a-efd36d2ab538.png)

**Comment by manateelazycat** [comment]
> 我的意思是：之前用的`point-at-bol`，跟现在用的`line-end-position`，在通过 `(and ...)` 判断的时候都会返回一个数值，实际上是不起作用的（也就是说，即便撤回了上个补丁，也还是跟现在一样的效果）
> 
> 疑问是：这里这样写的目的是什么

这是你写的补丁多写了一个 nil, 不是原版的问题。

**Comment by dalugm** [comment]
> 这是你写的补丁多写了一个 nil

抱歉，可能是改别的地方的时候误加上了，但这跟我问的问题没关系😓

因为 `point-at-eol` 和 `line-end-position` 这俩函数无论有没有后面那个 `nil` 参数，它们返回的值都是一致的，我的问题是这个函数在这里起什么作用。。

**Comment by manateelazycat** [comment]
grammatical-edit-in-comment-p 函数的作用是， grammatical-edit-node-type-at-point 在行尾会探测不出来是 comment 的类型， 如果光标在行尾需要退后一个字符再判断

point-at-eol的意思光标是否在行尾

**Comment by dalugm** [comment]
> point-at-eol的意思光标是否在行尾

不是这样的大佬😂，`point-at-eol` 返回光标所在行最后一个字符的位置，跟 `line-end-position` 返回的值一样，是个数，而不是 `t` 或者 `nil`；如果要判断是否在行尾，不是应该用我在一楼说的方法吗？

**Comment by manateelazycat** [comment]
> > point-at-eol的意思光标是否在行尾
> 
> 不是这样的大佬joy，`point-at-eol` 返回光标所在行最后一个字符的位置，跟 `line-end-position` 返回的值一样，是个数，而不是 `t` 或者 `nil`；如果要判断是否在行尾，不是应该用我在一楼说的方法吗？

嗯， 你是对的， 这几天合并补丁太多了，脑袋不清醒。

那麻烦这个补丁和上一个补丁（我看有几个 nil 多加了）合并再发一个补丁吧， 谢谢。

**Comment by dalugm** [comment]
大佬客气了，我正在看您的代码学习，能帮上忙就最好不过了

> 我看有几个 nil 多加了

我加了 nil 参数的函数是 `looking-back`, `looking-back` 这个函数的原型是 `(looking-back REGEXP LIMIT &optional GREEDY)`，如果不加的话 Emacs 也默认是给加上了 `nil`，需要去掉吗？（我加上主要是防止编译的时候出 warning，虽然不影响使用，但看着糟心😂）

**Comment by manateelazycat** [comment]
> 大佬客气了，我正在看您的代码学习，能帮上忙就最好不过了
> 
> > 我看有几个 nil 多加了
> 
> 我加了 nil 参数的函数是 `looking-back`, `looking-back` 这个函数的原型是 `(looking-back REGEXP LIMIT &optional GREEDY)`，如果不加的话 Emacs 也默认是给加上了 `nil`，需要去掉吗？（我加上主要是防止编译的时候出 warning，虽然不影响使用，但看着糟心😂）

looking-back 那几个加吧，我主要对改这么多地方补丁，测试强度比较大。

**Comment by dalugm** [comment]
好的哈，我都是自己测过了没问题再给提交补丁，大佬可以稍微放下心
