### ISSUE TITLE
python字符串删除问题

### ISSUE THREAD

**Issue by lynnux** [manateelazycat/grammatical-edit#2]
测试修改 https://github.com/emacs-eaf/emacs-application-framework/blob/master/install-eaf.py#L111 这行，想要删除掉`, '--user'`在不动用region的情况下，只用`grammatical-edit-backward-delete`发现待''包含的字符串都删除完后，''删除不掉，配合`grammatical-edit-forward-delete`也删除不了，甚至把[]里全部字符串都删除后，[]里还留有一对''删除不了。
录了个gif如图
![GIF 2021-11-29 12-11-44](https://user-images.githubusercontent.com/367894/143808238-42fe223c-a1cc-4fa3-9043-81b492b98654.gif)
：

**Comment by manateelazycat** [comment]
@lynnux 更新最新版再测试一下。

**Comment by lynnux** [comment]
`grammatical-edit-backward-delete`没问题了，但是`grammatical-edit-forward-delete`好像没有处理，比如|"aaaa"，在|的位置，删除没有反应。

**Comment by manateelazycat** [comment]
> `grammatical-edit-backward-delete`没问题了，但是`grammatical-edit-forward-delete`好像没有处理，比如|"aaaa"，在|的位置，删除没有反应。

我一会看看

**Comment by manateelazycat** [comment]
> `grammatical-edit-backward-delete`没问题了，但是`grammatical-edit-forward-delete`好像没有处理，比如|"aaaa"，在|的位置，删除没有反应。

再更新试一下吧，切换 tree-sitter 后，这几个函数确实没有重新测试过了。

**Comment by lynnux** [comment]
运行良好！ 不过测试`aa = "|"""`，当在|位置按`grammatical-edit-forward-delete`后直接删除成只剩aa了，如图：

![GIF 2021-11-30 9-42-52](https://user-images.githubusercontent.com/367894/143970380-b1a706e2-dc66-45c1-b4a4-49942ed2dc6d.gif)

**Comment by lynnux** [comment]
`grammatical-edit-forward-delete`测试`time.strftime("%Y-%m-%d |%H:%M:%S", time.localtime())`在|删除也有问题：
![GIF 2021-11-30 10-14-56](https://user-images.githubusercontent.com/367894/143973516-8d02e92d-38d7-4e82-ba56-6374a4679a51.gif)

**Comment by manateelazycat** [comment]
> 运行良好！ 不过测试`aa = "|"""`，当在|位置按`grammatical-edit-forward-delete`后直接删除成只剩aa了，如图：
> 
> ![GIF 2021-11-30 9-42-52](https://user-images.githubusercontent.com/367894/143970380-b1a706e2-dc66-45c1-b4a4-49942ed2dc6d.gif)

我没有重现你说的情况，极端情况就不测试了，我们就看看正常的那些还有漏掉的。

**Comment by manateelazycat** [comment]
> `grammatical-edit-forward-delete`测试`time.strftime("%Y-%m-%d |%H:%M:%S", time.localtime())`在|删除也有问题： ![GIF 2021-11-30 10-14-56](https://user-images.githubusercontent.com/367894/143973516-8d02e92d-38d7-4e82-ba56-6374a4679a51.gif)

这个情况确实是bug, 更新测试一下吧，已经修复。

**Comment by manateelazycat** [comment]
有新的问题再提新的Issue吧。
