### ISSUE TITLE
Commands for select/delete region within/with quotes/pairs/brackets?

### ISSUE THREAD

**Issue by liebkne** [manateelazycat/grammatical-edit#6]

**Comment by manateelazycat** [comment]
> _No description provided._

can you give an example?

**Comment by liebkne** [comment]
Hi, I mean can we mark or kill regions between `""/{}/[]`s (inclusively or exclusively with the quotes/brackets) using this awesome library?

**Comment by manateelazycat** [comment]
PR are welcome. ;)
