### ISSUE TITLE
grammatical-edit-forward-delete和grammatical-edit-backward-delete不修改kill ring? 

### ISSUE THREAD

**Issue by lynnux** [manateelazycat/grammatical-edit#9]
如题，或者增加选项到达该目的

**Comment by manateelazycat** [comment]
为什么要修改 kill-ring ?

**Comment by lynnux** [comment]
比如选中一些内容后，调用`grammatical-edit-forward-delete`，https://github.com/manateelazycat/grammatical-edit/blob/6b6a7bc1615b3294ec14ac9db970768b8c7b97b8/grammatical-edit.el#L270 会导致kill ring添加了被删除的内容，`grammatical-edit-backward-delete`没发现`region-active-p`的检测，但测试删除后region也是添加到kill ring里面了

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/grammatical-edit/commit/3d6b6f8a8cc6a0ca85df080622c03544e31d659f

**Comment by manateelazycat** [comment]
更新到最新版，设置选项 ```(setq grammatical-edit-save-in-kill-ring nil)```, 默认放到 kill-ring 其实非常方便，比如删除括号中的内容，移动光标到别的地方进行删除，这种效率比较高，不用手动选择括号内的边界。

**Comment by lynnux** [comment]
谢谢，这个新选项是对所有操作都生效，我的意思是能不能区分开，只在C-H(grammatical-edit-backward-delete)和C-D(grammatical-edit-forward-delete)里禁止保存到kill-ring，而C-W和C-K还是存到kill-ring。

**Comment by manateelazycat** [comment]
> 谢谢，这个新选项是对所有操作都生效，我的意思是能不能区分开，只在C-H(grammatical-edit-backward-delete)和C-D(grammatical-edit-forward-delete)里禁止保存到kill-ring，而C-W和C-K还是存到kill-ring。

不会这样设计，把事情搞的太复杂了
